ARG RUBY_VERSION=3.3.4

FROM ruby:$RUBY_VERSION-bullseye AS base

ENV RAILS_ENV=development

FROM base
ARG BUNDLER_VERSION=2.4.10

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev

COPY Gemfile Gemfile.lock ./

RUN gem install bundler:$BUNDLER_VERSION \
    && gem update --system \
    && gem install tzinfo-data \
    && gem install nokogiri \
    && gem install kamal

RUN echo 'gem: --no-document' >> ~/.gemrc \
    && bundle install

WORKDIR /weather-captcha

COPY . .
